version: "3.9"

services:
  flask_app:
    container_name: task_management_app
    build: .     # Use the Dockerfile in the current directory
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://postgres:postgres@tma_db:5432/postgres
      - SECRET_KEY=mynameisharishsatheesh
    depends_on:
      - tma_db
  tma_db:
    container_name: tma_db
    image: postgres:12
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes: 
  pgdata: {}
